name: build

on:
  push:
    branches: [ "debian" ]

jobs:
  deb-armhf:

    runs-on: ubuntu-latest
    container:
      image: debian:latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Add foreign (armhf) architecture
      run: dpkg --add-architecture armhf
    - name: Update package lists
      run: apt update
    - name: Install development dependencies
      run: apt install build-essential devscripts equivs crossbuild-essential-armhf --yes --no-install-recommends
    - name: Get and install build package dependencies
      run: mk-build-deps --tool='apt-get -o Debug::pkgProblemResolver=yes --no-install-recommends --yes' debian/control -i --host-arch armhf
    - name: Rename source file to negate need for source tgz
      run: mv debian/source/format debian/source/format.1
    - name: Build debian package
      run: CONFIG_SITE=/etc/dpkg-cross/cross-config.amd64 DEB_BUILD_OPTIONS=nocheck dpkg-buildpackage -aarmhf -Pcross,nocheck
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        path: ../libdrm*.*
      
      
